// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqg5sA55Fa19mnG7Ew4LTwC1VnLPUYGKQ',
    appId: '1:333666174023:web:0fbdc13c64eb5b85a55d62',
    messagingSenderId: '333666174023',
    projectId: 'controle-viagens-9a288',
    authDomain: 'controle-viagens-9a288.firebaseapp.com',
    storageBucket: 'controle-viagens-9a288.firebasestorage.app',
    measurementId: 'G-V4K5NG8Z5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVnYOmjXfqcJsx7VrLst3ctHwzva4Gxy4',
    appId: '1:333666174023:android:90cc77ba2d138203a55d62',
    messagingSenderId: '333666174023',
    projectId: 'controle-viagens-9a288',
    storageBucket: 'controle-viagens-9a288.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqg5sA55Fa19mnG7Ew4LTwC1VnLPUYGKQ',
    appId: '1:333666174023:web:0da92e597f14162ba55d62',
    messagingSenderId: '333666174023',
    projectId: 'controle-viagens-9a288',
    authDomain: 'controle-viagens-9a288.firebaseapp.com',
    storageBucket: 'controle-viagens-9a288.firebasestorage.app',
    measurementId: 'G-2QFVX0SPFV',
  );
}
